### ISSUE TITLE
please add support for API level 14

### ISSUE THREAD

**Issue by linsea** [sprylab/texturevideoview#10]
hi sir, thanks for providing this great widget, I have a requirement:  clould you add support for API level 14 (android 4.0), what's the problem(get rid of the method calls which rely on API > 14 ) if you support this version?

**Comment by rzimmer** [comment]
Currently, Android support starts at version 4.0.3 (API level 15). API level 14 is not listed on the [official Google Dashboards](http://developer.android.com/about/dashboards/index.html) for a long time now (less than 0.1% distribution). Could you please provide a list of all offending methods which prevent API level 14? I then might think about it, but can't promise it yet...

**Comment by linsea** [comment]
I found only one method call relies on API Level 15:
`
getSurfaceTexture().setDefaultBufferSize(mVideoWidth, mVideoHeight);
`
could it be bypassed ?

**Comment by rzimmer** [comment]
I'm not sure if bypassing is possible without breaking behavior. It's hard for me to test, too, because I have no API-14 device available. You may fork and test bypassing on a corresponding device and give feedback or even better a PR.

**Comment by rzimmer** [comment]
No feedback anymore, closing...
