### ISSUE TITLE
Video And Audio Takes Too Much Time To Load

### ISSUE THREAD

**Issue by amitdesale** [sprylab/texturevideoview#12]
I use this code but while loading video and audio takes too much time to load

**Comment by rzimmer** [comment]
I don't think, we can do anything here. The library is based on the official `VideoView` sources, so I assume that using the `VideoView` from Android you will experience the same performance issues. You might give it a try and report back. Maybe the source of all this lies in the video file itself!?

**Comment by rzimmer** [comment]
No feedback anymore, closing...

**Comment by midhilajm** [comment]
i am also facing same issue .it take long time to play

**Comment by midhilajm** [comment]
please reopen this

**Comment by hameno** [comment]
Hello,
we are currently not maintaining this project.
As we've said before, this project is only a small change compared to the original VideoView.
Please test with the platform VideoView or preferably switch to using ExoPlayer.
