### ISSUE TITLE
No instructions to build the library

### ISSUE THREAD

**Issue by ezaquarii** [sprylab/texturevideoview#13]
Instructions to build the library are not working.

```
gradle compile 'com.sprylab.android.texturevideoview:texturevideoview:1.1.1'

FAILURE: Build failed with an exception.

* What went wrong:
Task 'compile' not found in root project 'texturevideoview'.
```

```
gradle init
:wrapper UP-TO-DATE
:init
Maven to Gradle conversion is an incubating feature.
:init FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':init'.
> Could not convert Maven POM /home/tn/Devel/texturevideoview/pom.xml to a Gradle build.
   > Unable to create Maven project model using POM /home/tn/Devel/texturevideoview/pom.xml.
      > Cycle detected in component graph in the system:
```

**Comment by rzimmer** [comment]
You wrongly confused the Gradle dependency declaration with commands for building the library. This project uses Maven as a build tool. There are currently no explicit instructions needed to build the library except for the default, well-known Maven commands: `mvn clean package` (see [Maven in 5 Minutes](https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html) for more information about Maven).

**Comment by ezaquarii** [comment]
Geezus, it was a monumental brain eclipse. :/ Sorry.
