### ISSUE TITLE
apk

### ISSUE THREAD

**Issue by jjhesk** [sprylab/texturevideoview#2]
does it have an sample apk?

**Comment by rzimmer** [comment]
Sorry, there's no pre-compiled sample APK yet, so you have to compile it for your own at the moment. But good point, though. We might really offer one in the future...

**Comment by rzimmer** [comment]
Sorry, I must have been dizzy... We already had an pre-compiled sample APK just from the start published to Maven Central. Here it is for the current version: [Download](http://search.maven.org/remotecontent?filepath=com/sprylab/android/texturevideoview/sample/1.0.1/sample-1.0.1.apk)
