### ISSUE TITLE
TextureVideoView: Error: 1,-12

### ISSUE THREAD

**Issue by andrefpc** [sprylab/texturevideoview#20]
A found this error, but I have no idea how to fix.

**Comment by rzimmer** [comment]
Unfortunately, this error message does not provide information, what went wrong. There may be issues with the video, the connection or the device.

Do you have any more context? A stacktrace, other log output from ADB, example code, device information or whatever.
Without this, we can't help you, I'm afraid...

**Comment by andrefpc** [comment]
My code is this:

```
TextureVideoView  videoTutorial = layout.findViewById(R.id.video_tutorial);

Uri uri = Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + object.getVideoResourceId());

videoTutorial.setVideoURI(uri);

videoTutorial.start();
```

But, I use the TextureVideoView into a ViewPager with fragments.
My ViewPager have 4 pages and run videos in loop to make a tutorial, 3 of 4 videos run normally, but 1 of then give me this error and not run!

My log returns this errors:

01-15 11:12:20.405 W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
01-15 11:12:20.437 D/MediaPlayer: setSubtitleAnchor in MediaPlayer
01-15 11:12:20.519 E/MediaPlayer: error (1, -12)
01-15 11:12:20.521 E/MediaPlayer: Error (1,-12)
01-15 11:12:20.521 D/TextureVideoView: Error: 1,-12

**Comment by rzimmer** [comment]
Can you double check that the video, which is not working, is not corrupt and correctly encoded to work on Android devices? Seems to me an issue with the file itself, not with TextureVideoView, because your other 3 videos work correctly. TextureVideoView just propagates the error of the underlying [MediaPlayer](https://developer.android.com/reference/android/media/MediaPlayer.html) - which is actually responsible for decoding - like shown in the logs...

**Comment by andrefpc** [comment]
This codes works normally in most of Android devices that i test, only in one device I have a problem.

**Comment by rzimmer** [comment]
So, what's the problematic device? Manufacturer, Model? Does Android's VideoView work with the file? Maybe it's a system resource issue. Do you correctly release the media player and destroy your views in the ViewPager by calling `TextureVideoView.stopPlayback()`? What is your offscreen page limit?
