### ISSUE TITLE
will be back screen

### ISSUE THREAD

**Issue by wangbin0802** [sprylab/texturevideoview#21]
When switch to other activity then go back ,the screen will black flash.
In some low level phone like xiaomiMax

**Comment by rzimmer** [comment]
Is this behaviour reproducible with the Android's VideoView, too? Do you pause the video playback - ideally on the underlying [MediaPlayer](https://developer.android.com/reference/android/media/MediaPlayer.html) object - in `onPause()` and resume playback in `onResume()`?

**Comment by hameno** [comment]
No response
