### ISSUE TITLE
After unlocking device video doesn't resume or start

### ISSUE THREAD

**Issue by artakhnoyan** [sprylab/texturevideoview#22]

**Comment by rzimmer** [comment]
You as a developer are responsible for pausing and resuming the video. So this is no issue with TextureVideoView as Android's VideoView behaves exactly the same.

See e.g. https://stackoverflow.com/questions/7289515/videoview-pausing-and-resuming for approaches using `onPause()` and `onResume()`.

Closing this issue now...
