### ISSUE TITLE
how to mute and un mute the video ?

### ISSUE THREAD

**Issue by husseinAYehya** [sprylab/texturevideoview#23]

**Comment by rzimmer** [comment]
As `TextureVideoView` is a drop-in replacement for Android's `VideoView`, there is nothing else to do as if you were working with `VideoView` directly. Please look how to (un-)mute `VideoView`. Here are some resources for you to get started:

- https://stackoverflow.com/questions/12435275/mute-a-playing-video-by-videoview-in-android-application
- https://stackoverflow.com/questions/13394876/muting-a-video-in-a-videoview
