### ISSUE TITLE
OnPrepared listener is called only once

### ISSUE THREAD

**Issue by dioseltorre** [sprylab/texturevideoview#24]
I'm creating a slideshow with images and videos using [ViewFlipper](https://developer.android.com/reference/android/widget/ViewFlipper) with animations. I starts the video automatically in `onPrepared()` callback when it is the current displayed view. Please see sample code below:
```
videoView.setOnPreparedListener(new MediaPlayer.OnPreparedListener() {
            @Override
            public void onPrepared(MediaPlayer mp) {
                mViewFlipper.stopFlipping();
                mp.start();
            }
});
```

The video plays automatically for the first time it is displayed but on the next cycle it doesn't play anymore, hence, the `onPrepared()` callback is not called again. I tried using the native Android [VideoView](https://developer.android.com/reference/android/widget/VideoView) and it will always play automatically in each cycle.

Any help/suggestion would be greatly appreciated. Thanks in advance.

**Comment by rzimmer** [comment]
Normally, the `OnPreparedListener` should only be called once by definition as it signals that the video is loaded successfully and ready for playback. Don't know, why this seems to work with native `VideoView` as we don't do anything special here in comparison to it.

You might try to invoke the private `openVideo()` method, which is accessible through the public `resume()` method or whenever the video path or URL is (re-)set with `setVideoPath()` or `setVideoURI`). It will call `onPrepared()` internally.

I don't even think that the `OnPreparedListener` is the right event to listen to, but the one, when the view is flipped by the `ViewFlipper`. You might find here a more reliable way to auto play your videos (`videoView.seekTo(0); videoView.resume();`): https://stackoverflow.com/questions/3813108/listener-for-viewflipper-widget-flipping-events
