### ISSUE TITLE
TextureView not working with seekbar

### ISSUE THREAD

**Issue by mavencode01** [sprylab/texturevideoview#4]
I tried to use your library but I can't get the seekbar to work....is this a problem when extending `TextureView`

Any ideas

**Comment by rzimmer** [comment]
I can't imagine that as the `TextureView` is only used for rendering. The rest should behave exactly the same as a normal `VideoView`. Please try if the seekbar is working when you use a normal `VideoView`. If it does, then replace `VideoView` with the `TextureVideoView` and see if it's still working. It should - but if not, please provide some code samples. Thank you!

**Comment by mavencode01** [comment]
I would expect the same also, will try it out and let you know - thanks

**Comment by mavencode01** [comment]
Works now, thanks
