### ISSUE TITLE
onCompletion-callback hit only once

### ISSUE THREAD

**Issue by MrNovado** [sprylab/texturevideoview#6]
```
if (mCurrentState == STATE_PLAYBACK_COMPLETED) {
    // sprylab bugfix: on some devices onCompletion is called twice
    return;
}
mCurrentState = STATE_PLAYBACK_COMPLETED;
mTargetState = STATE_PLAYBACK_COMPLETED;
```

This actually breaks the initial behavior since onCompletion-callback wont be hit more than once at all.
Which is a problem if we want, for example, positioned looping:

```
video.seekTo(data.get(position).startingPosition)
video.start()
```

**Comment by rzimmer** [comment]
Mh, thinking about that I believe you're right. You could always guard the execution of the onCompletion-callback in your client code if you really run into problems with multiple calls to it. I will revert this to the original behavior in the next release of this library.

**Comment by linsea** [comment]
I found this issue as well when I wrote my library:https://github.com/linsea/UniversalVideoView , this should be a android framework bug,  maybe we should report it to google android team.
