### ISSUE TITLE
Scale type support

### ISSUE THREAD

**Issue by pavlo-zin** [sprylab/texturevideoview#9]
Any plans for implementing scaling support?

**Comment by rzimmer** [comment]
You mean like in [Android-ScalableVideoView](https://github.com/yqritc/Android-ScalableVideoView)? It's not planned as TextureVideoView tries to be a as-pure-as-possible drop-in replacement of Android's VideoView based on the original sources. Of course, you are free to call `TextureVideoView#setTransform(Matrix)` from outside to apply any transformation matrix you like. But in general it's very unlikely that we add features that are not included in the original (besides additions from TextureView, obviously).

**Comment by pavlo-zin** [comment]
OK, thanks for clarifying that. 

I managed to implement scaling by taking some logic from [Android-ScalableVideoView](https://github.com/yqritc/Android-ScalableVideoView) and integrating it with TextureVideoView.

You can check it out [here](https://gist.github.com/paulzin/6c9eaf92ccc156dd9608).

**Comment by rzimmer** [comment]
Great example, good to know that it's works for you! Thanks for sharing and using TextureVideoView :smile:
